eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: ${eureka_url:http://192.168.60.254:8761/eureka/}
      defaultZone: discovery-service:8761/eureka/
    instance:
      hostname: discovery-service
      # hostname: 192.168.60.254
      # prefer-ip-address: true
