eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: discovery-service
      # hostname: localhost
