eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/ #it can be able in local computer
    instance:
      hostname: localhost
      # hostname: localhost #it can be able in local computer
