eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.31.0.2:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: 172.31.0.2
      # hostname: localhost
