eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.32.2:8761/eureka}
      # defaultZone: http://localhost:8761/eureka/
    instance:
      # hostname: localhost
      hostname: 192.168.32.2
      prefer-ip-address: true
